swagger: '2.0'
info:
  description: Open LIMS
  version: 1.0.0
  title: Open LIMS API's
basePath: /api/
tags:
  - name: Sample

paths:
  /v1/sample:
    get:
      tags:
        - Sample
      summary: Get All
      operationId: getAllSamples
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
    post:
      tags:
        - Sample
      summary: 'Create One or Many (optional: create with tests and/or storage location)'
      operationId: createOneOrManySamples
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: samples
          type: array
          required: true
          items:
            type: string
          example: {
            "samples": [
              {
                "sample_type": "Urine",
                "internalId": "29-6976",
                "externalId": "99-2206",
                "customer_id": 92,
                "value_unit": "1.00",
                "status": "In Hold",
                "unit": "µL",
                "collected_date": "1988-06-05 16:39:49",
                "collected_by_id": 71,
                "received_date": "2021-02-09 11:01:41",
                "received_by_id": 80,
                "description": null,
                "discarded_date": null,
                "storage_id": 1,
                "tests": [
                  {
                    "analysis_id": 14
                  },
                  {
                    "analysis_id": 20
                  }
                ]
              },
              {
                "sample_type": "Blood",
                "internalId": "29-6976",
                "externalId": "99-2206",
                "customer_id": 92,
                "value_unit": "1.00",
                "status": "In Hold",
                "unit": "µL",
                "collected_date": "1988-06-05 16:39:49",
                "collected_by_id": 71,
                "received_date": "2021-02-09 11:01:41",
                "received_by_id": 80,
                "description": null,
                "discarded_date": null,
              }
            ]
          }
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
      security:
        - api_key: []
  /v1/sample/findByIds/{ids}:
    get:
      tags:
        - Sample
      summary: Find By Ids
      operationId: findSamplesByIds
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: ids
          type: string
          value: 1,2,3
          required: true
      responses:
        '200':
          description: successful operation
  /v1/sample/updateByIds:
    patch:
      tags:
        - Sample
      summary: Update or Restore SoftDeleted By Ids
      operationId: updateSamplesByIds
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: samples
          type: array
          required: true
          items:
            type: string
          example: {
            "samples": [
              {
                "id": 1,
                "sample_type": "Urine",
                "internalId": "29-6976",
                "externalId": "99-2206",
                "customer_id": 92,
                "value_unit": "1.00",
                "status": "In Hold",
                "unit": "µL",
                "collected_date": "1988-06-05 16:39:49",
                "collected_by_id": 71,
                "received_date": "2021-02-09 11:01:41",
                "received_by_id": 80,
              },
              {
                "id": 2,
                "sample_type": "Blood",
                "internalId": "29-6976",
                "externalId": "99-2206",
                "customer_id": 92,
                "value_unit": "1.00",
                "status": "In Hold",
                "unit": "µL",
                "collected_date": "1988-06-05 16:39:49",
                "collected_by_id": 71,
                "received_date": "2021-02-09 11:01:41",
                "received_by_id": 80
              },
              {
                "id": 3,
                "restore": "true"
              }
            ]
          }
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  /v1/sample/{id}:
    delete:
      tags:
        - Sample
      summary: Soft delete
      operationId: destroySample
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          value: 3
          required: true
      responses:
        '200':
          description: successful operation

  /v1/enum/{name}:
    get:
      tags:
        - Enum
      summary: Get Values By Name
      description: 'Enums available: "CustodyType", "SampleType", "Status", "StorageType" and "UnitMeasurement"'
      operationId: enum
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          type: string
          value: CustodyType
          required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
